name: Build

env:
  # deploymentNameBuild: ${{ github.event.inputs.deploymentNameBuild }}
  # location: ${{ github.event.inputs.location }}
  deploymentNameBuild: 'deployBedrock'
  buildBicepPath: './deploy/build/main.bicep'
  timeZone: 'Europe/Amsterdam'
  startTime: '13:00'
  endTime: '20:00'
  gameMode: 'survival'
  gameDifficulty: 'normal'
  gameAllowCheats: 'true'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # LOGIN TO AZURE. THE LOGGED IN SESSION IS ACTIVE TILL A LOGOUT ACTION IS CALLED (OR THE JOB FINISHED)
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      # SET CORRECT AZURE CONTEXT
      - name: 'Set context to subscription'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-AzContext -Subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azPSVersion: "latest"
      
      # VALIDATE BICEP
      - name: 'Set context to subscription'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az bicep build --file '${{ env.buildBicepPath }}'
          azPSVersion: "latest"

      # DEPLOY THE SERVICES
      - name: 'Create / Update Azure resources'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            New-AzSubscriptionDeployment -name '${{ env.deploymentNameBuild }}' -namePrefix '${{ secrets.PREFIX }}' -location '${{ secrets.LOCATION }}' -timeZone '${{ env.timeZone }}' -startTime '${{ env.startTime }}' -endTime '${{ env.endTime }}' -gameMode '${{ env.gameMode }}' -gameDifficulty '${{ env.gameDifficulty }}' -gameAllowCheats '${{ env.gameAllowCheats }}' -TemplateFile '${{ env.buildBicepPath }}'
          azPSVersion: "latest"

      # LOGOUT
      - name: logout
        run: |
          az logout